package uk.co.frankz.hmcts.dts.aws.dynamodb;

import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedUuid;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;
import uk.co.frankz.hmcts.dts.model.EntityWithId;
import uk.co.frankz.hmcts.dts.model.Status;
import uk.co.frankz.hmcts.dts.model.Task;

import java.time.LocalDateTime;

/**
 * Class TaskWithId represents entity Task, with the addition
 * that has an identity, which is implemented by DynamoDB.
 * <br>
 * The separation of the id and the domain fields is a result
 * of adding some framework implementation (Spring or EclipseStore)
 * for storing entities after the domain fields where created.
 */
@DynamoDbBean
public class TaskWithId extends Task implements EntityWithId {

    private String id;

    public TaskWithId() {
        super();
    }

    public TaskWithId(Task original) {
        super(original);
        if (original instanceof EntityWithId) {
            this.id = ((EntityWithId) original).getId();
        }
    }

    public boolean isNew() {
        return id == null;
    }

    @Override
    @DynamoDbPartitionKey
    @DynamoDbAutoGeneratedUuid
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Override
    @DynamoDbAttribute("title")
    public String getTitle() {
        return super.getTitle();
    }

    @Override
    @DynamoDbAttribute("due")
    public LocalDateTime getDue() {
        return super.getDue();
    }

    @Override
    @DynamoDbAttribute("desc")
    public String getDescription() {
        return super.getDescription();
    }

    @Override
    @DynamoDbAttribute("status")
    public Status getStatus() {
        return super.getStatus();
    }

    @Override
    public String toString() {
        return "TaskWithId{"
            + "id='" + id + '\''
            + ", " + super.toString()
            + '}';
    }

}
