package uk.co.frankz.hmcts.dts.aws.dynamodb;

import jakarta.validation.constraints.NotNull;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbConvertedBy;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;
import uk.co.frankz.hmcts.dts.model.EntityWithId;
import uk.co.frankz.hmcts.dts.model.ITask;
import uk.co.frankz.hmcts.dts.model.Status;
import uk.co.frankz.hmcts.dts.model.Task;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Class TaskWithId represents entity Task, with the addition
 * that has an identity, which is implemented by DynamoDB.
 * <br>
 * The separation of the id and the domain fields is a result
 * of adding some framework implementation (Spring or EclipseStore)
 * for storing entities after the domain fields where created.
 * <br>
 * A DynamoDbBean picks up all "properties" that have a getter
 * and setter. The getters are overridden so that it can have
 * special tags. The setters for the "properties" need to return
 * void, and can be in the Task super class.
 */
@DynamoDbBean
public class TaskWithId extends Task implements ITask, EntityWithId {

    private UUID id;

    public boolean isNew() {
        return id == null;
    }

    @Override
    public String getId() {
        return id == null ? null : id.toString();
    }

    /**
     * Auto-generating uuid value.
     * Tag @DynamoDbAutoGeneratedUuid
     * does result in generating an id for storing in the database,
     * but would not set it on this pojo, so no way to return that id with @DynamoDbAutoGeneratedUuid.
     *
     * @return a UUID value that previously is set, otherwise is generated on the fly.
     */
    @NotNull
    @DynamoDbAttribute("id")
    @DynamoDbPartitionKey
    @DynamoDbConvertedBy(AutoUuidConverter.class)
    public UUID getUUID() {
        if (id == null) {
            id = UUID.randomUUID();
        }
        return id;
    }

    public void setUUID(UUID id) {
        this.id = id;
    }

    @Override
    @DynamoDbAttribute("title")
    public String getTitle() {
        return super.getTitle();
    }

    @Override
    @DynamoDbAttribute("due")
    @DynamoDbConvertedBy(IsoDateTimeConverter.class)
    public LocalDateTime getDue() {
        return super.getDue();
    }

    @Override
    @DynamoDbAttribute("desc")
    public String getDescription() {
        return super.getDescription();
    }

    @Override
    @DynamoDbAttribute("status")
    @DynamoDbConvertedBy(StatusConverter.class)
    public Status getStatus() {
        return super.getStatus();
    }

    @Override
    public String toString() {
        return "TaskWithId{"
            + "id='" + id + '\''
            + ", " + super.toString()
            + '}';
    }

}
