package uk.co.frankz.hmcts.dts.aws.dynamodb;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import software.amazon.awssdk.auth.credentials.AwsCredentialsProvider;
import software.amazon.awssdk.enhanced.dynamodb.DynamoDbEnhancedClient;
import software.amazon.awssdk.enhanced.dynamodb.DynamoDbTable;
import software.amazon.awssdk.enhanced.dynamodb.Key;
import software.amazon.awssdk.enhanced.dynamodb.TableSchema;
import software.amazon.awssdk.enhanced.dynamodb.extensions.AutoGeneratedUuidExtension;
import software.amazon.awssdk.enhanced.dynamodb.model.DescribeTableEnhancedResponse;
import software.amazon.awssdk.regions.Region;
import software.amazon.awssdk.services.dynamodb.DynamoDbClient;
import software.amazon.awssdk.services.dynamodb.model.TableStatus;
import uk.co.frankz.hmcts.dts.aws.TaskProperties;
import uk.co.frankz.hmcts.dts.model.exception.TaskStoreException;
import uk.co.frankz.hmcts.dts.service.TaskStore;

import java.util.Optional;

import static uk.co.frankz.hmcts.dts.aws.Mapper.JACKSON;

public class TaskStoreImpl implements TaskStore<TaskWithId> {

    private static final Logger LOG = LoggerFactory.getLogger(TaskStoreImpl.class);

    private final DynamoDbTable<TaskWithId> table;

    public TaskStoreImpl(AwsCredentialsProvider credentials) {

        DynamoDbClient dynamoAccess = DynamoDbClient.builder()
            .credentialsProvider(credentials)
            .region(Region.EU_WEST_1)
            .build();

        DynamoDbEnhancedClient client = DynamoDbEnhancedClient
            .builder()
            .dynamoDbClient(dynamoAccess)
            .extensions(AutoGeneratedUuidExtension.create())
            .build();

        table = client.table(TaskProperties.TABLE, TableSchema.fromBean(TaskWithId.class));
    }

    public <S extends TaskWithId> S save(S entity) {

        try {
            if (entity.isNew()) {

                // UUID is generated during putItem()
                table.putItem(entity);

                LOG.info("After putItem the id is generated: " + entity);
            } else {
                table.updateItem(entity);
            }
        } catch (Exception e) {
            LOG.error("Save failed: ", e);
            throw new TaskStoreException(e);
        }

        return entity;
    }

    public Optional<TaskWithId> findById(String id) {

        Key findKey = Key.builder().partitionValue(id).build();
        TaskWithId found = null;

        try {
            found = table.getItem(findKey);
        } catch (Exception e) {
            LOG.warn(e.toString());
        }
        return Optional.ofNullable(found);
    }

    public void deleteById(String id) {

        Key findKey = Key.builder().partitionValue(id).build();
        try {
            table.getItem(findKey);
        } catch (Exception e) {
            LOG.warn("Silent delete - " + e.toString());
        }

    }

    public Iterable<TaskWithId> findAll() {

        try {
            return table.scan().items().stream().toList();
        } catch (Exception e) {
            LOG.error("Scan failed: ", e);
            throw new TaskStoreException(e);
        }
    }

    public void healthCheck() {
        TableStatus status;
        try {
            DescribeTableEnhancedResponse desc = table.describeTable();
            healthCheckLog(desc);
            status = desc.table().tableStatus();
        } catch (Exception e) {
            throw new TaskStoreException("HealthCheck", e);
        }

        if (TableStatus.ACTIVE != status) {
            throw new TaskStoreException("HealthCheck: Expected " + TableStatus.ACTIVE + " but was " + status + ".");
        }
    }

    private void healthCheckLog(DescribeTableEnhancedResponse jsonObject) {
        if (LOG.isDebugEnabled()) {
            try {
                LOG.debug(JACKSON.writeValueAsString(jsonObject));
            } catch (Exception e) {
                LOG.warn(e.toString());
            }
        }
    }
}
