package uk.co.frankz.hmcts.dts.aws.dynamodb;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import software.amazon.awssdk.enhanced.dynamodb.extensions.AutoGeneratedUuidExtension;
import software.amazon.awssdk.enhanced.dynamodb.model.DescribeTableEnhancedResponse;
import software.amazon.awssdk.services.dynamodb.model.TableStatus;
import uk.co.frankz.hmcts.dts.aws.Properties;
import uk.co.frankz.hmcts.dts.model.exception.TaskStoreException;
import uk.co.frankz.hmcts.dts.service.TaskStore;

import java.util.Optional;

import static uk.co.frankz.hmcts.dts.aws.Mapper.JACKSON;

/**
 * The implementation class that uses AWS DynamoDb to persist, retrieve, and delete Tasks.
 */
public class TaskStoreImpl implements TaskStore<TaskWithId> {

    private static final Logger LOG = LoggerFactory.getLogger(TaskStoreImpl.class);

    private final DynamoDbTableProvider<TaskWithId> table;

    public TaskStoreImpl() {
        this(new DynamoDbTableProvider<>(Properties.TABLE, TaskWithId.class, AutoGeneratedUuidExtension.create()));
    }

    public TaskStoreImpl(DynamoDbTableProvider<TaskWithId> table) {
        this.table = table;
    }

    public <S extends TaskWithId> S save(S entity) {

        try {
            if (entity.isNew()) {

                // UUID is generated during putItem()
                table.save(entity);

                LOG.info("After putItem the id is generated: " + entity);
            } else {
                table.update(entity);
            }
        } catch (Exception e) {
            throw new TaskStoreException(e);
        }

        return entity;
    }

    public Optional<TaskWithId> findById(String id) {

        return Optional.ofNullable(table.find(id));
    }

    public void deleteById(String id) {
        table.delete(id);
    }

    public Iterable<TaskWithId> findAll() {

        try {
            return table.findAll();
        } catch (Exception e) {
            throw new TaskStoreException(e);
        }
    }

    public void healthCheck() {
        TableStatus status;
        try {
            DescribeTableEnhancedResponse desc = table.describe();
            healthCheckLog(desc);
            status = desc.table().tableStatus();
        } catch (Exception e) {
            throw new TaskStoreException("HealthCheck", e);
        }

        if (TableStatus.ACTIVE != status) {
            throw new TaskStoreException("HealthCheck: Expected " + TableStatus.ACTIVE + " but was " + status + ".");
        }
    }

    private void healthCheckLog(DescribeTableEnhancedResponse jsonObject) {
        if (LOG.isDebugEnabled()) {
            try {
                LOG.debug(JACKSON.writeValueAsString(jsonObject));
            } catch (Exception e) {
                LOG.warn(e.toString());
            }
        }
    }
}
