package uk.co.frankz.hmcts.dts.aws.lambda;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;
import com.amazonaws.services.lambda.runtime.events.APIGatewayV2HTTPEvent;
import com.amazonaws.services.lambda.runtime.events.APIGatewayV2HTTPResponse;
import io.swagger.v3.oas.annotations.Operation;
import org.apache.commons.lang3.NotImplementedException;
import org.apache.commons.lang3.tuple.Pair;
import org.springframework.web.bind.annotation.GetMapping;
import uk.co.frankz.hmcts.dts.model.exception.TaskException;
import uk.co.frankz.hmcts.dts.service.Action;

import java.util.Map;

public class RootTaskHandler extends BaseTaskHandler
    implements RequestHandler<APIGatewayV2HTTPEvent, APIGatewayV2HTTPResponse> {

    private static final String BODY_FORMAT = "<!DOCTYPE html><html>"
        + "<head><title>Success</title></head>"
        + "<body>"
        + "<h1>Welcome</h1>"
        + "<p>Page generated by a Lambda function.</p>"
        + "%s"
        + "</body></html>";

    @Operation(summary = "Redirect to a success icon on the WWW site.")
    @GetMapping(Action.PATH.ROOT)
    @Override
    public APIGatewayV2HTTPResponse handleRequest(APIGatewayV2HTTPEvent input, Context context) {

        var response = new APIGatewayV2HTTPResponse();

        try {
            service.healthCheck();

            // if health
            response.setStatusCode(200);
            response.setBody(body("OK"));
            response.setHeaders(Header.HTML);

        } catch (TaskException e) {
            response.setStatusCode(200);
            response.setBody(body(e.getMessage()));
            response.setHeaders(Header.HTML);
        }

        return response;
    }

    @Override
    protected Pair<String, Integer> handle(Action action, String requestBody, Map<String, String> pathParams)
        throws Exception {
        // should not come here
        throw new NotImplementedException(
            "handleRequest is overridden to allow redirection, so handle is not implemented.");
    }

    private String body(String message) {
        return BODY_FORMAT.formatted(message);
    }
}
