package uk.co.frankz.hmcts.dts.aws.lambda;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;
import com.amazonaws.services.lambda.runtime.events.APIGatewayV2HTTPEvent;
import com.amazonaws.services.lambda.runtime.events.APIGatewayV2HTTPResponse;
import io.swagger.v3.oas.annotations.Operation;
import org.apache.commons.lang3.tuple.Pair;
import org.springframework.web.bind.annotation.GetMapping;
import uk.co.frankz.hmcts.dts.aws.Mapper;
import uk.co.frankz.hmcts.dts.aws.dynamodb.TaskWithId;
import uk.co.frankz.hmcts.dts.model.exception.TaskException;
import uk.co.frankz.hmcts.dts.service.Action;
import uk.co.frankz.hmcts.dts.service.Header;
import uk.co.frankz.hmcts.dts.service.TaskService;

import java.util.Map;

public class RootTaskHandler extends BaseTaskHandler
    implements RequestHandler<APIGatewayV2HTTPEvent, APIGatewayV2HTTPResponse> {

    /**
     * Required constructor for the Lambda getting initialised. A so-called warm container constructor.
     */
    public RootTaskHandler() {
        super();
    }

    /**
     * Constructor allowing unit test with mocks.
     *
     * @param service allows unit testing with mock TaskService
     * @param json    allows unit testing with mock Mapper
     */
    RootTaskHandler(TaskService<TaskWithId> service, Mapper json) {
        super(service, json);
    }

    private static final String BODY_FORMAT = "<!DOCTYPE html><html>"
        + "<head><title>Success</title></head>"
        + "<body>"
        + "<h1>Welcome</h1>"
        + "<p>Page generated by a Lambda function.</p>"
        + "%s"
        + "</body></html>";

    @Operation(summary = "Redirect to a success icon on the WWW site.")
    @GetMapping(Action.PATH.ROOT)
    @Override
    public APIGatewayV2HTTPResponse handleRequest(APIGatewayV2HTTPEvent input, Context context) {

        var response = new APIGatewayV2HTTPResponse();

        try {
            Pair<String, Integer> result = handle(null, null, null);

            response.setStatusCode(result.getRight());
            response.setBody(body(result.getLeft()));
            response.setHeaders(Header.HTML);

        } catch (Exception e) {

            response.setStatusCode(500);
            response.setBody(body(e.getMessage()));
            response.setHeaders(Header.HTML);
        }

        return response;
    }

    @Override
    protected Pair<String, Integer> handle(Action action, String requestBody, Map<String, String> pathParams)
        throws Exception {

        try {
            service.healthCheck();

            // if healthty
            return Pair.of("OK", 200);

        } catch (TaskException e) {
            return Pair.of(e.getMessage(), 200);
        }
    }

    private String body(String message) {
        return BODY_FORMAT.formatted(message);
    }
}
