package uk.co.frankz.hmcts.dts.aws.lambda;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;
import com.amazonaws.services.lambda.runtime.events.APIGatewayV2HTTPEvent;
import com.amazonaws.services.lambda.runtime.events.APIGatewayV2HTTPResponse;
import io.swagger.v3.oas.annotations.Operation;
import uk.co.frankz.hmcts.dts.aws.Mapper;
import uk.co.frankz.hmcts.dts.aws.dynamodb.TaskWithId;
import uk.co.frankz.hmcts.dts.aws.http.IdemPotencyScopeKeyBuilder;
import uk.co.frankz.hmcts.dts.aws.http.ResponseFields;
import uk.co.frankz.hmcts.dts.model.exception.TaskException;
import uk.co.frankz.hmcts.dts.service.Action;
import uk.co.frankz.hmcts.dts.service.Header;
import uk.co.frankz.hmcts.dts.service.IdemPotencyStore;
import uk.co.frankz.hmcts.dts.service.TaskService;

import java.util.Map;

public class RootTaskHandler extends BaseTaskHandler
    implements RequestHandler<APIGatewayV2HTTPEvent, APIGatewayV2HTTPResponse> {

    /**
     * Required constructor for the Lambda getting initialised. A so-called warm container constructor.
     */
    @SuppressWarnings("unused")
    public RootTaskHandler() {
        super();
    }

    /**
     * Constructor allowing unit test with mocks.
     *
     * @param service          allows unit testing with mock TaskService
     * @param json             allows unit testing with mock Mapper
     * @param idemPotency      the builder for IdemPotencyScopeKey
     * @param idemPotencyStore the dynamoDb table
     */
    RootTaskHandler(TaskService<TaskWithId> service,
                    Mapper json,
                    IdemPotencyScopeKeyBuilder idemPotency,
                    IdemPotencyStore idemPotencyStore) {
        super(service, json, idemPotency, idemPotencyStore);
    }

    private static final String BODY_FORMAT = "<!DOCTYPE html><html>"
        + "<head><title>Success</title></head>"
        + "<body>"
        + "<h1>Welcome</h1>"
        + "<p>Page generated by a Lambda function.</p>"
        + "%s"
        + "</body></html>";

    @Operation(summary = "Redirect to a success icon on the WWW site.")
    //@GetMapping(Action.PATH.ROOT)
    @Override
    public APIGatewayV2HTTPResponse handleRequest(APIGatewayV2HTTPEvent input, Context context) {

        var response = new APIGatewayV2HTTPResponse();

        try {
            ResponseFields result = handle(null, null, null);

            response.setStatusCode(result.status());
            response.setBody(body(result.body()));
            response.setHeaders(Header.HTML);

        } catch (Exception e) {

            response.setStatusCode(500);
            response.setBody(body(e.getMessage()));
            response.setHeaders(Header.HTML);
        }

        return response;
    }

    @Override
    protected ResponseFields handle(Action action, String requestBody, Map<String, String> pathParams)
        throws Exception {

        try {
            service.healthCheck();

            // if healthty
            return new ResponseFields("OK", 200, Header.HTML);

        } catch (TaskException e) {
            return new ResponseFields(e.getMessage(), 200, Header.HTML);
        }
    }

    private String body(String message) {
        return BODY_FORMAT.formatted(message);
    }
}
