package uk.co.frankz.hmcts.dts.aws;

import com.amazonaws.services.lambda.runtime.events.APIGatewayV2HTTPResponse;
import uk.co.frankz.hmcts.dts.model.exception.IdemPotencyException;
import uk.co.frankz.hmcts.dts.model.exception.IdemPotencyIssue;
import uk.co.frankz.hmcts.dts.model.exception.IdemPotencyRuntimeException;
import uk.co.frankz.hmcts.dts.model.exception.TaskException;
import uk.co.frankz.hmcts.dts.service.Header;

import static software.amazon.awssdk.http.HttpStatusCode.BAD_REQUEST;
import static software.amazon.awssdk.http.HttpStatusCode.INTERNAL_SERVER_ERROR;

public class TaskExceptionHandler {

    /**
     * On an error, HTML is prepared with some feedback.
     * The HTTP status code is 400 for a application wrapped exception
     * and a 500 for an exception that was not wrapped, so not expected.
     *
     * @param e        exception
     * @param response is a html page with some feedback
     */
    public static void setErrorOnResponse(Exception e, APIGatewayV2HTTPResponse response) {

        final String message;
        final int statusCode;

        // With Java 21 we could do this with switch
        if (e instanceof TaskException) {
            statusCode = BAD_REQUEST;
            message = TaskException.toString(e);
        } else if (e instanceof IdemPotencyRuntimeException idre) {
            statusCode = idre.getIssue().getHttpStatus();
            message = IdemPotencyIssue.toString(idre);
        } else if (e instanceof IdemPotencyException ide) {
            statusCode = ide.getIssue().getHttpStatus();
            message = IdemPotencyIssue.toString(ide);
        } else {
            statusCode = INTERNAL_SERVER_ERROR;
            message = TaskException.toString(e);
        }

        response.setBody(body(message));
        response.setStatusCode(statusCode);
        response.setHeaders(Header.HTML);
    }

    private static String body(String msg) {

        return
            "<!DOCTYPE html><html>"
                + "<head><title>Lambda</title></head>"
                + "<body>"
                + "<h1>Error</h1><p>Page generated by a Lambda function.</p>"
                + msg
                + "</body></html>";
    }

}
