package uk.co.frankz.hmcts.dts.aws;

import com.amazonaws.services.lambda.runtime.events.APIGatewayV2HTTPResponse;
import uk.co.frankz.hmcts.dts.model.exception.TaskException;
import uk.co.frankz.hmcts.dts.service.Header;

public class TaskExceptionHandler {

    public static void setErrorOnResponse(Exception e, APIGatewayV2HTTPResponse response) {

        String message = TaskException.toString(e);
        int statusCode = e instanceof TaskException ? 400 : 500;

        response.setBody(body(message));
        response.setStatusCode(statusCode);
        response.setHeaders(Header.HTML);
    }

    private static String body(String msg) {

        return
            "<!DOCTYPE html><html>"
                + "<head><title>Lambda</title></head>"
                + "<body>"
                + "<h1>Error</h1><p>Page generated by a Lambda function.</p>"
                + msg
                + "</body></html>";
    }

}
